### ISSUE TITLE
doesn't work with python 2.5

### ISSUE THREAD

**Issue by joernhees** [acdha/nose-congestion#4]
Python 2.5 didn't have the str.format, maybe use % instead?

```
Location                                       Total    setUp tearDown
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.5/bin/nosetests", line 9, in <module>
    load_entry_point('nose==1.3.0', 'console_scripts', 'nosetests')()
  File "/home/travis/virtualenv/python2.5/lib/python2.5/site-packages/nose/core.py", line 118, in __init__
    **extra_args)
  File "/usr/lib/python2.5/unittest.py", line 768, in __init__
    self.runTests()
  File "/home/travis/virtualenv/python2.5/lib/python2.5/site-packages/nose/core.py", line 197, in runTests
    result = self.testRunner.run(self.test)
  File "/home/travis/virtualenv/python2.5/lib/python2.5/site-packages/nose/core.py", line 63, in run
    result.printErrors()
  File "/home/travis/virtualenv/python2.5/lib/python2.5/site-packages/nose/result.py", line 110, in printErrors
    self.config.plugins.report(self.stream)
  File "/home/travis/virtualenv/python2.5/lib/python2.5/site-packages/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/home/travis/virtualenv/python2.5/lib/python2.5/site-packages/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "/home/travis/virtualenv/python2.5/lib/python2.5/site-packages/nose_congestion.py", line 76, in report
    print >>stream, fmt.format(context_name, **times)
AttributeError: 'str' object has no attribute 'format'
```

**Comment by acdha** [comment]
I haven't used Python 2.5 in quite awhile so I'm unlikely to make this change. If you still need Python 2.5 support, feel free to send a pull request after it's working.

**Comment by skudriashev** [comment]
@joernhees, is this issue still valid or we can close it?

**Comment by joernhees** [comment]
we dropped support for py2.5 when travis-ci dropped it. depends on what you want to support i guess.

**Comment by skudriashev** [comment]
When I don't see any reasons to fix this issue.

**Comment by skudriashev** [comment]
@acdha, shell you close this issue, please?)
