### ISSUE TITLE
doesn't work with python 3

### ISSUE THREAD

**Issue by joernhees** [acdha/nose-congestion#5]
use of print >>

```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.2/bin/nosetests", line 9, in <module>
    load_entry_point('nose==1.3.0', 'console_scripts', 'nosetests')()
  File "/home/travis/virtualenv/python3.2/lib/python3.2/site-packages/nose/core.py", line 118, in __init__
    **extra_args)
  File "/usr/lib/python3.2/unittest/main.py", line 124, in __init__
    self.runTests()
  File "/home/travis/virtualenv/python3.2/lib/python3.2/site-packages/nose/core.py", line 197, in runTests
    result = self.testRunner.run(self.test)
  File "/home/travis/virtualenv/python3.2/lib/python3.2/site-packages/nose/core.py", line 63, in run
    result.printErrors()
  File "/home/travis/virtualenv/python3.2/lib/python3.2/site-packages/nose/result.py", line 110, in printErrors
    self.config.plugins.report(self.stream)
  File "/home/travis/virtualenv/python3.2/lib/python3.2/site-packages/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/home/travis/virtualenv/python3.2/lib/python3.2/site-packages/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "/home/travis/virtualenv/python3.2/lib/python3.2/site-packages/nose_congestion.py", line 69, in report
    print >>stream, "%-43s %8s %8s %8s" % ('Location', 'Total',
TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and '_WritelnDecorator'
```

**Comment by skudriashev** [comment]
Looks like this one is done and may be closed.

**Comment by acdha** [comment]
Completed
